### PR TITLE
Add SRV record support

### PR DESCRIPTION
**Pull request by Kamesuta**
# Problem
Some servers use Minecraft SRV record for use.

# Fix
Add DNS SRV record resolving.
(so host and ip test are not suitable)

### CODE REVIEW

**Comment by PassTheMayo** [comment]
Although I think that your code would be helpful to many, I do not think that this functionality should be left up to the library itself. Also, your previous pull request made this request have merge conflicts.

**Comment by Kamesuta** [comment]
So need an option to enable/disable SRV feature?

**Comment by PassTheMayo** [comment]
Yeah, I'll allow that. If you could add an option to disable SRV lookup, I'll merge. Also, could you rewrite lines 30 and 31 to be more standard? I'm trying to remain some compatibility with older Node versions, and I'm sure those lines contain new ECMA features.

**Comment by Kamesuta** [comment]
Okay, I added `enableSRV` option and backward compatible.

**Comment by PassTheMayo** [comment]
Awesome! I'll upgrade the package version and publish to npm in a minute.

**Pull request merged**
